language: objective-c
osx_image: xcode8.3
os: osx

before_install:
  - brew tap osrf/ros2
  - brew tap ros/deps
#  - brew unlink numpy
  - brew install python3 wget cppcheck gtest tinyxml eigen pcre # cmake already installed
  - brew install asio tinyxml2
  - brew tap homebrew/science
#  - brew install opencv --without-python
  - sudo -H python3 -m pip install empy setuptools nose vcstool pep8 pydocstyle pyflakes flake8 mock coverage

script:
  - /bin/echo "Hello world"
  - /bin/pwd
  - sh build_travis_macos.sh
